### ISSUE TITLE
Mount point not found

### ISSUE THREAD

**Issue by ghost** [ReSqAr/kcb#1]
Hi, I get the following error message although I can access my cell phone via Dolphin.

Any idea what it could be?

![Screenshot_20201013_165847](https://user-images.githubusercontent.com/57014294/95878559-a5dd2380-0d75-11eb-8d26-5bb5e80f440c.png)
![Screenshot_20201013_170155](https://user-images.githubusercontent.com/57014294/95878843-f2286380-0d75-11eb-923e-7e05d087a6a8.png)

**Comment by ReSqAr** [comment]
Hi n1qu! Sorry for coming back on this earlier. kcb expects that you namedyour storage location `All Files`, which I think is the standard or at least was the standard when I first configured KDE Connect on my phone. For future reference, what this means is that on your phone, you have to go to `Plugin Settings -> Filesystem Expose` and create an endpoint called `All Files`. In your case, the endpoint was called `nico` if I understand the screenshot correctly. You could also change the code, the logic is encoded [here](https://github.com/ReSqAr/kcb/blob/master/kcb/kcb.py#L117).
